language: generic
sudo: required
services:
    - docker


before_install:
    - docker build -t noiz564/docker-react -f Dockerfile.dev .

script:
    - docker run noiz564/docker-react npm run test -- --coverage